name: ci-cd
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]

jobs:
  mob-pipeline:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: unittest

    steps:
      - uses: actions/checkout@v3

      - name: install dependencies
        run: yarn

      - name: run unit test coverage
        run: yarn run coverage
